title: Tempfiles
description: ""
url: "tempfiles.carlgo11.com"
permalink: pretty
markdown: kramdown
img: /img/favicon.png
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - .gitignore
sass:
  style: compressed
