sudo: false

matrix:
  include:
    - language: php
      php:
        - 7.2
        - 7.3
      before_install:
        - cd backend
      install:
        - composer install
      script:
        - phpunit --configuration phpunit.xml
      cache:
        directories:
          - $HOME/.composer/cache
    - language: ruby
      rvm:
        - 2.4.1
      cache: bundler
      before_install:
        - cd frontend