title: Tempfiles
description: "Upload files securely over the internet for 24 hours."
permalink: pretty
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .github
  - .gitignore
  - .editorconfig
  - .idea
  - LICENSE
  - CNAME
  - README.md
sass:
  sass_dir: css
  style: compressed
urls:
  upload: "https://api.tempfiles.download/upload/"
  download: "https://d.tempfiles.download/"
  delete: "http://api.tempfiles.download/delete/"
