title: Tempfiles
description: "Upload files securely over the internet for 24 hours."
url: "tempfiles.carlgo11.com"
download_url: "https://d.carlgo11.com/"
permalink: pretty
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - .idea
sass:
  style: compressed
