title: Tempfiles
description: "Upload files securely over the internet for 24 hours."
permalink: pretty
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - .idea
  - README.md
