title: Tempfiles
description: "Upload files securely over the internet for 24 hours."
url: "tempfiles.carlgo11.com"
permalink: pretty
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - .gitignore
sass:
  style: compressed
