version: '3'
services: 
  tempfiles:
    image: jekyll/jekyll
    volumes:
      - ./:/srv/jekyll
    command: jekyll build
    environment:
      - JEKYLL_UID=1001
      - JEKYLL_GID=1001
      - VERBOSE="true"
