name: Test Jekyll

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    name: Jekyll - Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler

      - name: Install dependencies
        run: sudo snap install ruby --classic

      - name: Run Bundler
        run: bundle install --path vendor/bundle

      - name: Build the site
        run: bundle exec jekyll build --future
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
