# Test Jekyll frontend site. Only run when the commit contains changes to the directory '/frontend'.
name: Test Jekyll

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    name: Jekyll - Test & Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
