name: Test PHPUnit

on:
  push:
    paths:
      - 'backend/*'
  pull_request:
    paths:
      - 'backend/*'

jobs:
  build:
    name: PHPUnit - Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: backend

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit -c phpunit.xml --teamcity
      working-directory: backend
